[package]
name = "rust-ray-trace"
version = "0.1.0"
keywords = ["raytracer"]
categories = ["rendering"]
authors = ["Johann Muszynski <johann.muszynski@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.11.2"
rand = "0.6"
